- **`try`, `catch`, `finally`** 捕获和处理代码块中可能发生的错误。
	```
	try {
	} catch (e) {
	} finally {
	}
	```
- **`throw`** 抛出一个自定义错误。
- **Error Object (错误对象)** 表示错误的内置对象。
	```
	newError("Something went wrong");
	```
- **Custom Errors (自定义错误)** 通过继承 `Error` 类来创建特定的错误类型。
	```
	classAuthErrorextendsError{}
	```
- **Stack Trace (堆栈跟踪)** 错误发生时函数调用的路径记录，用于调试。